name: Update World Cup iCal

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests ics

      - name: Generate iCal
        run: |
          python script/update_worldcup_ics.py

      - name: Commit result
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/worldcup_cn.ics
          git commit -m "Update iCal" || echo "No changes"
          git push
